### ISSUE TITLE
Создать worker для kafka

### ISSUE THREAD

**Issue by alexseipopov** [s21platform/friends-service#10]
Необходимо создать воркера (в файле cmd/workers/notification/main.go) 
Воркер подрубается к кафке и консьюмит его (подключается к топику). Создадим в .env переменные FRIENDS_SERVICE_NOTIFICATION_KAFKA_TOPIC и NOTIFICATION_SERVICE_FRIENDS_TOPIC) локально можете задать какое угодно строковое значение - по сути это имя для канала из которого читать и куда записывать (на сервере будут свои значения, так что правда, как угодно назовите). Теперь самое главное поднять кафку у себя для локального тестирования. Прикрепляю сервисы, которые необходимо вставить в ваш docker-compose.yml файл, который напоминаю - мы не пушим)

```
zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
```

запускайте docker-compose - все должно запуститься

Далее необходимо создать топик в самой кафке, которую вы сейчас запустили. Делается командой:

`docker exec -it kafka kafka-topics --create --topic <___Тут имя, что вы в .env прописали____> --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1`

например: docker exec -it kafka kafka-topics --create --topic test_topic --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1

Теперь можно работать

----
## Для ручного тестирования что даные ваш сервис читает, тестовые данные можно отправить вручную, командой:

`docker exec -it kafka kafka-console-producer --topic <___Тут имя, что вы в .env прописали____> --bootstrap-server kafka:9092`

Запустится интерактивный режим, где можно просто передавать строки (в будущем там будем передавать stringify json которые будем парсить - тут всегда есть риск что придет невалидная для json строка, наше дело если произойдет ошибка - просто отбросить данные как не валидные и ждать сообщений дальше - вопрос валидации встанет на стороне записывающей.

## Для ручного чтения из топика:

`docker exec -it kafka kafka-console-consumer --topic <___Тут имя, что вы в .env прописали____> --bootstrap-server kafka:9092 --from-beginning`

учтите что считает все!

----

 # Резюмируя
Создаем воркера, который читает топик из FRIENDS_SERVICE_NOTIFICATION_KAFKA_TOPIC
получаем сейчас оттуда стрингой почту ищем по таблице peer_invite всех, кто такого пользователя приглашал, и их uuid отправляем в топик NOTIFICATION_SERVICE_FRIENDS_TOPIC (этот топик уже слушает другой сервис)
